optimizer_config:
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1e-3
      weight_decay: 9e-4
  lr_scheduler:
    scheduler:
      class_path: torch.optim.lr_scheduler.ExponentialLR
      init_args:
        gamma: 0.92
    # scheduler:
    #   class_path: torch.optim.lr_scheduler.MultiStepLR
    #   init_args:
    #     milestones: [8, 11]
    # warmup_config:
    #   warmup_iters: 600

trainer:
  max_epochs: 3
