trainer:
  logger:
    class_path: lightning_template.utils.loggers.wandb.WandbNamedLogger
    init_args:
      project: UNC-Project
      entity: wloner0809
      save_dir: work_dirs
      name: Medmcqa_llama_lora_freeze
      offline: false
      tags: []
  # not save ckpt here for saving disk space
  enable_checkpointing: false
  callbacks:
    - class_path: lightning_template.utils.progress.rich_progress.RichProgressBar
      init_args:
        show_version: false
        show_eta_time: true
    - class_path: lightning.pytorch.callbacks.RichModelSummary
      init_args:
        max_depth: 2
    - class_path: lightning_template.utils.callbacks.set_precision_and_cudnn_callback.SetPrecisionAndCudnnCallback
      init_args:
        float32_matmul_precision: high
        allow_fp16_reduced_precision_reduction: true
        deterministic_debug_mode: default
        cudnn_enabled: true
    - class_path: lightning_template.utils.callbacks.set_wandb_logger_callback.SetWandbLoggerCallback
      init_args:
        watch_model_cfg:
          log: all
    - class_path: lightning_template.utils.callbacks.custom_repr.CustomReprCallback
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
  # train len
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  # k fold cross validation
  num_folds: null
  # gradient clip
  gradient_clip_val: null
  gradient_clip_algorithm: null
  # debug
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  num_sanity_val_steps: null
  barebones: false
  detect_anomaly: false
  # speed up
  num_nodes: 1
  accelerator: auto
  devices: auto
  precision: bf16-true

  sync_batchnorm: false
  accumulate_grad_batches: 1
  use_distributed_sampler: true
  deterministic: null
  benchmark: null
  inference_mode: true
  # val and log
  check_val_every_n_epoch: 1
  val_check_interval: null
  log_every_n_steps: null
  # dataloader
  reload_dataloaders_every_n_epochs: 0

# seed
seed_everything: true
